import Peer from 'peerjs'
export class RoomNetwork {
 constructor(onUpdate,onError,PeerClass=Peer){this.PeerClass=PeerClass;this.onUpdate=onUpdate;this.onError=onError;this.connections=new Map();this.members=[];this.host=false;this.started=false;this.closed=false;this.handlers=new Set();this.timer=null;this.lastSeen=Date.now()}
 emit(data){for(const fn of this.handlers)fn(data)}
 subscribe(fn){this.handlers.add(fn);return()=>this.handlers.delete(fn)}
 update(){this.onUpdate({code:this.code,host:this.host,members:[...this.members],connected:true,myId:this.id,config:this.config})}
 open(profile,code,config){this.profile=profile;this.host=!code;this.config=config;this.code=code||Array.from(crypto.getRandomValues(new Uint8Array(6)),n=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[n%31]).join('');this.peer=new this.PeerClass(this.host?'strikezone-'+this.code:undefined,{debug:0});this.timer=setTimeout(()=>this.fail('Ulanish vaqti tugadi. Internetingizni tekshirib, qayta urinib ko‘ring.'),16000);this.peer.on('open',id=>{if(this.closed)return;this.id=id;if(this.host){clearTimeout(this.timer);this.members=[{id,name:profile.name,team:0,weapon:profile.weapon,skin:profile.skin}];this.update()}else{const c=this.peer.connect('strikezone-'+this.code,{reliable:true,metadata:{name:profile.name,weapon:profile.weapon,skin:profile.skin}});this.bind(c)}});this.peer.on('connection',c=>{if(!this.host){c.close();return}this.bind(c)});this.peer.on('error',e=>{const messages={'peer-unavailable':'Bu kodli xona topilmadi. Kodni tekshiring.','unavailable-id':'Xona kodi band. Qayta xona oching.','network':'Internet bilan aloqa uzildi.','server-error':'Xona xizmatiga ulanib bo‘lmadi.'};this.fail(messages[e.type]||'Ulanib bo‘lmadi. Boshqa tarmoqdan qayta urinib ko‘ring.')});this.peer.on('disconnected',()=>{if(!this.closed)this.fail('Xona xizmati bilan aloqa uzildi. Xonani qayta oching.')})}
 bind(c){c.on('open',()=>{if(this.closed){c.close();return}if(this.host){if(this.started||this.members.length>=this.config.size*2){c.send({type:'error',message:this.started?'Jang boshlangan. Keyingi jangni kuting.':'Xona to‘lgan.'});setTimeout(()=>c.close(),300);return}this.connections.set(c.peer,c);const count=this.members.filter(m=>m.team===0).length;const team=count>this.members.length-count?1:0;this.members.push({id:c.peer,name:String(c.metadata?.name||'Operator').slice(0,18),team,weapon:c.metadata?.weapon||'ak',skin:c.metadata?.skin||'standard'});this.broadcast({type:'lobby',members:this.members,config:this.config});this.update()}else{this.connections.set(c.peer,c);this.hostConnection=c}});c.on('data',data=>{if(!data||typeof data!=='object')return;if(this.host){if(!this.connections.has(c.peer))return;if(data.type==='input')this.emit({type:'input',id:c.peer,input:data.input});if(data.type==='ping')c.send({type:'pong',at:data.at})}else{if(c!==this.hostConnection)return;clearTimeout(this.timer);this.lastSeen=Date.now();if(data.type==='error'){this.fail(data.message);return}if(data.type==='lobby'){this.members=data.members;this.config=data.config;this.update()}if(data.type==='start'){this.started=true;this.config=data.config}this.emit(data)}});c.on('close',()=>{if(this.closed)return;this.connections.delete(c.peer);if(this.host){this.members=this.members.filter(m=>m.id!==c.peer);this.broadcast({type:'lobby',members:this.members,config:this.config});this.update();this.emit({type:'leave',id:c.peer})}else this.fail('Xona egasi aloqani uzdi. Bosh menyuga qayting va yangi xona oching.')});c.on('error',()=>{if(!this.closed)this.fail('Do‘stingiz bilan to‘g‘ridan-to‘g‘ri aloqa o‘rnatilmadi. Boshqa Wi-Fi yoki mobil tarmoqdan urinib ko‘ring.')})}
 start(){if(!this.host||this.started)return;this.started=true;const data={type:'start',config:this.config,members:this.members};this.broadcast(data);this.emit(data)}
 broadcast(data){for(const c of this.connections.values())if(c.open){try{if(data.type==='state'&&c.dataChannel?.bufferedAmount>128000)continue;c.send(data)}catch{/* close event handles unavailable peers */}}}
 sendInput(input){if(this.hostConnection?.open)this.hostConnection.send({type:'input',input})}
 fail(message){if(this.closed)return;this.onError(message);this.emit({type:'error',message});this.close()}
 close(){this.closed=true;clearTimeout(this.timer);for(const c of this.connections.values())c.close();this.connections.clear();this.peer?.destroy()}
}
