import * as THREE from 'three'
import { MAPS, SKINS } from './config.js'
const material=(color,roughness=.8)=>new THREE.MeshStandardMaterial({color,roughness,metalness:.15})
function cube(parent,w,h,d,x,y,z,mat){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function cylinder(parent,r1,r2,h,x,y,z,mat,segments=10){const m=new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,segments),mat);m.position.set(x,y,z);m.castShadow=true;parent.add(m);return m}
export function makeGun(weapon='ak',skinId='standard'){
 const g=new THREE.Group(),skin=SKINS.find(s=>s.id===skinId)||SKINS[0];const metal=material('#282c29',.4),body=material(skinId==='standard'?(weapon==='ak'?'#766341':'#59634f'):skin.color,.45),accent=material(skin.accent,.48),black=material('#171c19',.6);const long=weapon==='awp'?1.3:weapon==='mp5'?.7:1;
 cube(g,.14,.2,.49,0,0,0,body);cube(g,.11,.08,.43,0,.13,-.04,metal);cube(g,.12,.15,.35*long,0,.005,-.4,body);cube(g,.14,.06,.34*long,0,-.06,-.4,black);const barrel=cylinder(g,.025,.025,.39*long,0,.02,-.64*long,metal);barrel.rotation.x=Math.PI/2;const muzzle=cylinder(g,.038,.038,.07,0,.02,-.85*long,black);muzzle.rotation.x=Math.PI/2;
 const stock=cube(g,.1,.17,.32,0,-.02,.36,weapon==='ak'?body:black);stock.rotation.x=-.12;cube(g,.14,.22,.055,0,-.03,.54,black);const grip=cube(g,.085,.24,.11,0,-.2,.1,black);grip.rotation.x=-.25;const mag=cube(g,.095,weapon==='awp'?.16:.3,.14,0,-.22,-.12,weapon==='ak'?accent:metal);mag.rotation.x=weapon==='ak'?.17:0;cube(g,.03,.11,.08,0,.19,-.48,metal);cube(g,.07,.055,.025,0,.25,-.49,black);cube(g,.075,.08,.06,0,.2,.12,black);
 for(let n=0;n<7;n++)cube(g,.155,.012,.024,0,.1,-.26-n*.04,metal);for(let side=-1;side<=1;side+=2)for(let n=0;n<3;n++)cube(g,.005,.075,.035,side*.071,0,-.13+n*.095,accent);
 if(weapon==='awp'){const scope=cylinder(g,.065,.065,.37,0,.24,-.04,black);scope.rotation.x=Math.PI/2;const lens=new THREE.Mesh(new THREE.CircleGeometry(.052,20),new THREE.MeshStandardMaterial({color:'#68c0c9',metalness:.8,roughness:.1}));lens.position.set(0,.24,.146);g.add(lens);cube(g,.06,.09,.05,0,.15,.02,metal)}
 return g
}
function textTexture(text,bg='#8b896e',fg='#eeeece',w=512,h=256){const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);ctx.fillStyle=fg;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`bold ${h*.5}px Arial`;ctx.fillText(text,w/2,h/2);const texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;return texture}
function groundTexture(){const c=document.createElement('canvas');c.width=c.height=256;const ctx=c.getContext('2d');ctx.fillStyle='#a5a292';ctx.fillRect(0,0,256,256);let seed=42;for(let i=0;i<10000;i++){seed=(seed*16807)%2147483647;const x=seed%256;seed=(seed*16807)%2147483647;const y=seed%256;ctx.fillStyle=i%2?'#827b6928':'#d4c8a422';ctx.fillRect(x,y,2,2)}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(18,18);t.colorSpace=THREE.SRGBColorSpace;return t}
export class ArenaRenderer {
 constructor(container,config,profile){this.config=config;this.profile=profile;this.renderer=new THREE.WebGLRenderer({antialias:profile.quality!=='low',powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,profile.quality==='low'?1:1.6));this.renderer.shadowMap.enabled=profile.quality!=='low';this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.1;this.canvas=this.renderer.domElement;this.canvas.tabIndex=0;this.canvas.setAttribute('aria-label','STRIKEZONE 3D jang maydoni');container.appendChild(this.canvas);this.scene=new THREE.Scene();const map=MAPS[config.map];this.scene.background=new THREE.Color(map.sky);this.scene.fog=new THREE.Fog(map.fog,30,95);this.camera=new THREE.PerspectiveCamera(78,1,.06,150);this.camera.rotation.order='YXZ';this.scene.add(this.camera);this.models=new Map();this.effects=[];this.lastEvent=0;this.recoil=0;this.time=0;this.currentGun='';this.lastSpawn=0;this.scene.add(new THREE.HemisphereLight('#e6eee3','#77735b',2));const sun=new THREE.DirectionalLight('#fff1cf',3);sun.position.set(-24,38,19);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-40;sun.shadow.camera.right=40;sun.shadow.camera.top=35;sun.shadow.camera.bottom=-35;sun.shadow.normalBias=.025;this.scene.add(sun);this.createMap(map);this.handGroup=new THREE.Group();this.camera.add(this.handGroup);this.setGun(profile.weapon,profile.skin);this.resize=()=>{const w=container.clientWidth,h=container.clientHeight;this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()};this.resize();this.observer=new ResizeObserver(this.resize);this.observer.observe(container)}
 createMap(map){const floor=new THREE.Mesh(new THREE.PlaneGeometry(150,150),new THREE.MeshStandardMaterial({color:map.ground,map:groundTexture(),roughness:1}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;this.scene.add(floor);const dark=material('#454b40'),trim=material('#aaa18a');for(const b of map.boxes){const mat=material(b.color);cube(this.scene,b.w,b.h,b.d,b.x,b.h/2,b.z,mat);if(b.kind==='container'){for(let x=-b.w/2+.2;x<b.w/2;x+=.38){cube(this.scene,.045,b.h-.12,.06,b.x+x,b.h/2,b.z+b.d/2+.02,mat);cube(this.scene,.045,b.h-.12,.06,b.x+x,b.h/2,b.z-b.d/2-.02,mat)}for(let z=-b.d/2+.2;z<b.d/2;z+=.45){cube(this.scene,.065,b.h-.1,.045,b.x+b.w/2,b.h/2,b.z+z,mat);cube(this.scene,.065,b.h-.1,.045,b.x-b.w/2,b.h/2,b.z+z,mat)}cube(this.scene,b.w+.06,.09,b.d+.06,b.x,b.h,b.z,dark)}else if(b.kind==='crate'){for(const y of [.12,b.h-.12])cube(this.scene,b.w+.04,.09,b.d+.04,b.x,y,b.z,dark);cube(this.scene,.12,b.h,b.d+.05,b.x,b.h/2,b.z,trim)}else if(b.h>4){cube(this.scene,b.w+.05,.25,b.d+.05,b.x,b.h,b.z,dark)}}
 for(const [z,letter,color] of [[-22.45,'B','#b1543c'],[22.45,'A','#566d86']]){const sign=new THREE.Mesh(new THREE.PlaneGeometry(3,2),new THREE.MeshStandardMaterial({map:textTexture(letter,color),side:THREE.DoubleSide}));sign.position.set(0,3,z);if(z>0)sign.rotation.y=Math.PI;this.scene.add(sign)}
 const label=new THREE.Mesh(new THREE.PlaneGeometry(9,2.3),new THREE.MeshStandardMaterial({map:textTexture('STRIKEZONE','#3c4437','#d3debc',1024,256)}));label.position.set(-24.45,3,0);label.rotation.y=Math.PI/2;this.scene.add(label);
 for(let side=-1;side<=1;side+=2){for(let n=0;n<7;n++){const h=6+(n%3)*2;cube(this.scene,6,h,8,n*10-30,h/2,side*34,material(n%2?'#878b80':'#99978b'));for(let j=0;j<3;j++)cube(this.scene,.9,1.1,.06,n*10-32+j*2,h-2,side>0?29.95:-29.95,material('#374b4c'))}for(let n=0;n<3;n++){const x=-20+n*20;const pole=cylinder(this.scene,.065,.065,8,x,4,side*21,dark);pole.castShadow=false;cube(this.scene,1.3,.1,.35,x,8,side*21,dark)}}
 const paint=material('#d7c174');for(let n=0;n<7;n++)cube(this.scene,1.2,.009,.12,-21+n*7,.01,-18,paint);for(let n=0;n<7;n++)cube(this.scene,1.2,.009,.12,-21+n*7,.01,18,paint);
 for(const [x,z] of [[-21,-15],[21,15],[-20,13],[20,-13]]){for(let n=0;n<2;n++){cylinder(this.scene,.43,.43,1.2,x+n*.95,.6,z,material('#6c7259'));cylinder(this.scene,.45,.45,.07,x+n*.95,.12,z,dark);cylinder(this.scene,.45,.45,.07,x+n*.95,1.05,z,dark)}}
 }
 setGun(weapon,skin){if(this.currentGun===weapon+skin)return;this.handGroup.clear();this.gun=makeGun(weapon,skin);this.handGroup.add(this.gun);const sleeve=material('#596046'),glove=material('#292e25');const a=cube(this.handGroup,.11,.12,.34,.11,-.15,.25,sleeve);a.rotation.z=-.3;cube(this.handGroup,.12,.13,.16,.035,-.13,.09,glove);const b=cube(this.handGroup,.1,.12,.4,-.11,-.14,-.16,sleeve);b.rotation.y=.3;cube(this.handGroup,.13,.1,.13,-.04,-.09,-.34,glove);this.flash=new THREE.PointLight('#ffd477',0,5);this.flash.position.set(0,.02,-.9);this.gun.add(this.flash);this.currentGun=weapon+skin}
 makePlayer(p){const g=new THREE.Group();const suit=material(p.team===0?'#53667b':'#87704e'),armor=material('#343d35'),boots=material('#242a24'),skin=material('#ae9474'),helmet=material(p.team===0?'#485a6b':'#746443');cube(g,.64,.63,.35,0,1.05,0,suit);cube(g,.58,.45,.12,0,1.12,-.21,armor);for(const x of [-.18,.18])cube(g,.13,.14,.08,x,1.06,-.29,armor);const head=new THREE.Mesh(new THREE.SphereGeometry(.22,12,10),skin);head.position.y=1.61;g.add(head);const helm=new THREE.Mesh(new THREE.SphereGeometry(.25,12,8,0,Math.PI*2,0,Math.PI*.61),helmet);helm.position.y=1.67;g.add(helm);cube(g,.35,.12,.08,0,1.65,-.2,boots);cube(g,.31,.18,.15,0,1.48,-.1,armor);const legs=[];for(const x of [-.17,.17]){const leg=new THREE.Group();leg.position.set(x,.72,0);cube(leg,.23,.54,.26,0,-.27,0,suit);cube(leg,.24,.18,.37,0,-.64,-.05,boots);g.add(leg);legs.push(leg)}for(const x of [-.42,.42]){const arm=cube(g,.18,.55,.21,x,1.01,-.1,suit);arm.rotation.x=-.7;cube(g,.17,.16,.19,x,.85,-.31,boots)}const gun=makeGun(p.weapon,p.skin);gun.scale.setScalar(.75);gun.position.set(.18,1.03,-.37);g.add(gun);const marker=new THREE.Mesh(new THREE.OctahedronGeometry(.105),new THREE.MeshBasicMaterial({color:p.team===0?'#86bcff':'#f5b068'}));marker.position.y=2.16;g.add(marker);this.scene.add(g);return {g,legs,marker,weapon:p.weapon,gun}}
 render(state,id,input,dt,onEvent){this.time+=dt;const p=state.players.find(p=>p.id===id);if(!p)return;this.setGun(p.weapon,p.skin);const smooth=1-Math.exp(-22*dt);const eye=p.y+(p.crouch?1.03:1.65);const dest=new THREE.Vector3(p.x,eye,p.z);if(this.camera.position.distanceTo(dest)>5)this.camera.position.copy(dest);else this.camera.position.lerp(dest,smooth);this.camera.rotation.set(input.pitch+this.recoil*.14,input.yaw,0,'YXZ');this.recoil=Math.max(0,this.recoil-dt*5);const fov=input.aim?(p.weapon==='awp'?27:53):input.sprint&&p.moving?84:78;this.camera.fov=THREE.MathUtils.lerp(this.camera.fov,fov,smooth);this.camera.updateProjectionMatrix();const bob=p.moving?Math.sin(this.time*(input.sprint?15:10))*.013:Math.sin(this.time*2)*.002;const aim=input.aim?1:0;this.handGroup.position.lerp(new THREE.Vector3(.24*(1-aim),-.23-aim*.017+bob,-.4+this.recoil*.055),smooth);this.handGroup.rotation.set(p.reloading>0?-.5+Math.sin(p.reloading*4)*.17:0,0,p.reloading>0?-.38:bob*.3);this.handGroup.visible=p.health>0&&!(input.aim&&p.weapon==='awp');this.flash.intensity=Math.max(0,this.flash.intensity-dt*180);
 const ids=new Set(state.players.map(p=>p.id));for(const [key,m] of this.models)if(!ids.has(key)){this.scene.remove(m.g);this.models.delete(key)}for(const q of state.players){if(q.id===id)continue;let m=this.models.get(q.id);if(!m){m=this.makePlayer(q);this.models.set(q.id,m);m.g.position.set(q.x,q.y,q.z)}m.g.visible=q.health>0;if(m.g.position.distanceTo(new THREE.Vector3(q.x,q.y,q.z))>5)m.g.position.set(q.x,q.y,q.z);else m.g.position.lerp(new THREE.Vector3(q.x,q.y,q.z),smooth);m.g.rotation.y=q.yaw;m.g.scale.y=q.crouch?.68:1;m.legs.forEach((l,n)=>{l.rotation.x=q.moving?Math.sin(this.time*9+n*Math.PI)*.4:0});m.marker.visible=q.team===p.team;m.marker.rotation.y=this.time;if(m.weapon!==q.weapon){m.g.remove(m.gun);m.gun=makeGun(q.weapon,q.skin);m.gun.scale.setScalar(.75);m.gun.position.set(.18,1.03,-.37);m.g.add(m.gun);m.weapon=q.weapon}}
 for(const e of state.events||[]){if(e.id<=this.lastEvent)continue;this.lastEvent=e.id;if(state.time-e.time>.45)continue;onEvent?.(e);if(e.type==='shot'){if(e.player===id){this.recoil=1;this.flash.intensity=9}const geo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(...e.from),new THREE.Vector3(...e.to)]);const line=new THREE.Line(geo,new THREE.LineBasicMaterial({color:e.player===id?'#ffdf8e':'#fff2bb',transparent:true,opacity:.7}));this.scene.add(line);this.effects.push({mesh:line,life:.075});const spark=new THREE.Mesh(new THREE.SphereGeometry(.04,5,5),new THREE.MeshBasicMaterial({color:'#ffdc85'}));spark.position.set(...e.to);this.scene.add(spark);this.effects.push({mesh:spark,life:.14})}}
 for(let n=this.effects.length-1;n>=0;n--){const e=this.effects[n];e.life-=dt;if(e.life<=0){this.scene.remove(e.mesh);e.mesh.geometry.dispose();e.mesh.material.dispose();this.effects.splice(n,1)}}this.renderer.render(this.scene,this.camera)
 }
 dispose(){this.observer.disconnect();this.scene.traverse(o=>{o.geometry?.dispose();const mats=o.material?Array.isArray(o.material)?o.material:[o.material]:[];mats.forEach(m=>{m.map?.dispose();m.dispose()})});this.renderer.dispose();this.canvas.remove()}
}
