// Generated by scripts/embed-migrations.mjs.
export const migrations=[
  "CREATE TABLE IF NOT EXISTS `admin_audit` (\r\n\t`id` text PRIMARY KEY NOT NULL,\r\n\t`actor_id` text NOT NULL,\r\n\t`amount` integer NOT NULL,\r\n\t`created_at` integer NOT NULL,\r\n\tFOREIGN KEY (`actor_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action\r\n);",
  "CREATE TABLE IF NOT EXISTS `purchases` (\r\n\t`id` text PRIMARY KEY NOT NULL,\r\n\t`user_id` text NOT NULL,\r\n\t`kind` text NOT NULL,\r\n\t`item_id` text NOT NULL,\r\n\t`price` integer NOT NULL,\r\n\t`created_at` integer NOT NULL,\r\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action\r\n);",
  "CREATE UNIQUE INDEX IF NOT EXISTS `purchase_owned_unique` ON `purchases` (`user_id`,`kind`,`item_id`);",
  "CREATE TABLE IF NOT EXISTS `rate_limits` (\r\n\t`key` text PRIMARY KEY NOT NULL,\r\n\t`count` integer NOT NULL,\r\n\t`reset_at` integer NOT NULL\r\n);",
  "CREATE TABLE IF NOT EXISTS `sessions` (\r\n\t`token_hash` text PRIMARY KEY NOT NULL,\r\n\t`user_id` text NOT NULL,\r\n\t`expires_at` integer NOT NULL,\r\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade\r\n);",
  "CREATE INDEX IF NOT EXISTS `sessions_user_idx` ON `sessions` (`user_id`);",
  "CREATE TABLE IF NOT EXISTS `match_tickets` (\r\n\t`id` text PRIMARY KEY NOT NULL,\r\n\t`user_id` text NOT NULL,\r\n\t`issued_at` integer NOT NULL,\r\n\t`duration` integer NOT NULL,\r\n\t`completed` integer DEFAULT 0 NOT NULL,\r\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action\r\n);",
  "CREATE INDEX IF NOT EXISTS `tickets_user_idx` ON `match_tickets` (`user_id`);",
  "CREATE TABLE IF NOT EXISTS `users` (\r\n\t`id` text PRIMARY KEY NOT NULL,\r\n\t`username` text NOT NULL,\r\n\t`password_hash` text NOT NULL,\r\n\t`role` text DEFAULT 'player' NOT NULL,\r\n\t`coins` integer DEFAULT 1000 NOT NULL,\r\n\t`profile` text NOT NULL,\r\n\t`revision` integer DEFAULT 0 NOT NULL,\r\n\t`created_at` integer NOT NULL\r\n);",
  "CREATE UNIQUE INDEX IF NOT EXISTS `users_username_unique` ON `users` (`username`);"
];
